import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useConferenceStore } from '../store/useConferenceStore'
import { getResults } from '../lib/api'
import { SponsorPanel } from '../components/results/SponsorPanel'
import { SpeakerPanel } from '../components/results/SpeakerPanel'
import { VenuePanel } from '../components/results/VenuePanel'
import { PricingPanel } from '../components/results/PricingPanel'
import { GTMPanel } from '../components/results/GTMPanel'
import { OpsPanel } from '../components/results/OpsPanel'
import { ExportButton } from '../components/results/ExportButton'
import clsx from 'clsx'

const TABS = [
  { id: 'sponsor',   label: 'Sponsors',  icon: '💰' },
  { id: 'speaker',   label: 'Speakers',  icon: '🎤' },
  { id: 'ticketing', label: 'Ticketing', icon: '🎫' },
  { id: 'venue',     label: 'Venues',    icon: '🏛️' },
  { id: 'pricing',   label: 'Pricing',   icon: '📊' },
  { id: 'gtm',       label: 'GTM',       icon: '📣' },
  { id: 'ops',       label: 'Ops',       icon: '⚙️' },
]

export function ResultsPage() {
  const { sessionId, results, setAllResults, isComplete } = useConferenceStore()
  const navigate = useNavigate()
  const [activeTab, setActiveTab] = useState('sponsor')
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    if (!sessionId) { navigate('/'); return }
    if (!isComplete && Object.keys(results).length === 0) {
      setLoading(true)
      getResults(sessionId)
        .then((r) => setAllResults(r.results))
        .catch(console.error)
        .finally(() => setLoading(false))
    }
  }, [sessionId, isComplete])

  if (!sessionId) return null

  return (
    <div className="p-6 space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between">
        <div>
          <h1 className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>Results</h1>
          <p className="text-sm mt-1" style={{ color: 'var(--text-secondary)' }}>
            Complete conference plan generated by 7 AI agents
          </p>
        </div>
        <ExportButton />
      </div>

      {/* Tabs */}
      <div
        className="flex gap-1 p-1 rounded-xl overflow-x-auto"
        style={{ background: 'var(--bg-surface)', border: '1px solid var(--border-subtle)' }}
      >
        {TABS.map((tab) => (
          <button
            key={tab.id}
            onClick={() => setActiveTab(tab.id)}
            className={clsx(
              'flex items-center gap-1.5 px-3 py-2 rounded-lg text-sm font-medium whitespace-nowrap transition-all duration-150',
              activeTab === tab.id
                ? 'bg-accent-cyan/10 text-accent-cyan'
                : 'text-text-secondary hover:text-text-primary hover:bg-bg-elevated',
            )}
            style={{ color: activeTab === tab.id ? '#00E5FF' : undefined }}
          >
            <span>{tab.icon}</span>
            {tab.label}
          </button>
        ))}
      </div>

      {/* Panel content */}
      <div>
        {loading && (
          <div className="text-center py-16" style={{ color: 'var(--text-secondary)' }}>
            Loading results...
          </div>
        )}
        {!loading && (
          <>
            {activeTab === 'sponsor'   && <SponsorPanel />}
            {activeTab === 'speaker'   && <SpeakerPanel />}
            {activeTab === 'ticketing' && <TicketingFallback results={results} />}
            {activeTab === 'venue'     && <VenuePanel />}
            {activeTab === 'pricing'   && <PricingPanel />}
            {activeTab === 'gtm'       && <GTMPanel />}
            {activeTab === 'ops'       && <OpsPanel />}
          </>
        )}
      </div>
    </div>
  )
}

// Simple ticketing display (inline, no separate panel file needed)
function TicketingFallback({ results }: { results: ReturnType<typeof useConferenceStore>['results'] }) {
  const data = results.ticketing
  if (!data) return <EmptyState label="Ticketing" />
  return (
    <div className="space-y-4">
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {data.tiers?.map((tier) => (
          <div key={tier.tier} className="glass-card p-5 space-y-3">
            <p className="text-xs font-semibold uppercase tracking-wider" style={{ color: 'var(--accent-cyan)' }}>{tier.tier}</p>
            <p className="text-3xl font-extrabold" style={{ color: 'var(--text-primary)' }}>{tier.price.toLocaleString()}</p>
            <p className="text-xs" style={{ color: 'var(--text-secondary)' }}>{tier.availability}</p>
            <ul className="space-y-1">
              {tier.perks?.map((p) => (
                <li key={p} className="text-xs flex items-center gap-1.5" style={{ color: 'var(--text-secondary)' }}>
                  <span style={{ color: 'var(--accent-green)' }}>✓</span> {p}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
      <div className="glass-card p-4">
        <p className="text-sm font-semibold mb-1" style={{ color: 'var(--text-primary)' }}>Recommended Platform</p>
        <p className="text-sm" style={{ color: 'var(--accent-cyan)' }}>{data.recommended_platform}</p>
        <p className="text-sm mt-2" style={{ color: 'var(--text-secondary)' }}>{data.notes}</p>
      </div>
    </div>
  )
}

function EmptyState({ label }: { label: string }) {
  return (
    <div className="text-center py-16" style={{ color: 'var(--text-dim)' }}>
      {label} results not available yet. Run the agents first.
    </div>
  )
}
