import { useState, useEffect } from 'react'
import { useNavigate } from 'react-router-dom'
import { useConferenceStore } from '../store/useConferenceStore'
import { getResults } from '../lib/api'
import { SponsorPanel } from '../components/results/SponsorPanel'
import { SpeakerPanel } from '../components/results/SpeakerPanel'
import { VenuePanel } from '../components/results/VenuePanel'
import { PricingPanel } from '../components/results/PricingPanel'
import { GTMPanel } from '../components/results/GTMPanel'
import { OpsPanel } from '../components/results/OpsPanel'
import { ExportButton } from '../components/results/ExportButton'
import { FileText } from 'lucide-react'
import type { AllResults, TicketTier } from '../types'
import clsx from 'clsx'
import { OrbitLoader } from '../components/shared/OrbitLoader'

const TABS = [
  { id: 'sponsor',   label: 'Sponsors',  icon: '💰', color: '#FFD700' },
  { id: 'speaker',   label: 'Speakers',  icon: '🎤', color: '#00E5FF' },
  { id: 'ticketing', label: 'Ticketing', icon: '🎫', color: '#B388FF' },
  { id: 'venue',     label: 'Venues',    icon: '🏛️', color: '#00E676' },
  { id: 'pricing',   label: 'Pricing',   icon: '📊', color: '#FF6B35' },
  { id: 'gtm',       label: 'GTM',       icon: '📣', color: '#FF6B35' },
  { id: 'ops',       label: 'Ops',       icon: '⚙️', color: '#9898A0' },
]

export function ResultsPage() {
  const { sessionId, results, setAllResults, isComplete } = useConferenceStore()
  const navigate = useNavigate()
  const [activeTab, setActiveTab] = useState('sponsor')
  const [loading, setLoading] = useState(false)

  useEffect(() => {
    if (!sessionId) { navigate('/'); return }
    if (!isComplete && Object.keys(results).length === 0) {
      setLoading(true)
      getResults(sessionId)
        .then((r) => setAllResults(r.results))
        .catch(console.error)
        .finally(() => setLoading(false))
    }
  }, [sessionId, isComplete])

  if (!sessionId) return null

  const activeTabData = TABS.find(t => t.id === activeTab)

  return (
    <div className="p-6 space-y-6 animate-page-in">
      {/* Header */}
      <div className="flex items-start justify-between">
        <div>
          <div className="flex items-center gap-2 mb-1">
            <div className="w-8 h-8 rounded-lg flex items-center justify-center" style={{ background: 'rgba(179,136,255,0.12)' }}>
              <FileText size={15} color="#B388FF" />
            </div>
            <h1 className="text-2xl font-bold" style={{ color: 'var(--text-primary)' }}>Results</h1>
          </div>
          <p className="text-sm pl-10" style={{ color: 'var(--text-secondary)' }}>
            Complete conference plan · generated by 7 AI agents
          </p>
        </div>
        <ExportButton />
      </div>

      {/* Tabs */}
      <div
        className="flex gap-1 p-1 rounded-2xl overflow-x-auto"
        style={{ background: 'var(--bg-surface)', border: '1px solid var(--border-subtle)' }}
      >
        {TABS.map((tab) => {
          const isActive = activeTab === tab.id
          return (
            <button
              key={tab.id}
              onClick={() => setActiveTab(tab.id)}
              className={clsx(
                'flex items-center gap-2 px-4 py-2.5 rounded-xl text-sm font-semibold whitespace-nowrap transition-all duration-200',
              )}
              style={{
                background: isActive ? `${tab.color}18` : 'transparent',
                color: isActive ? tab.color : 'var(--text-secondary)',
                border: isActive ? `1px solid ${tab.color}30` : '1px solid transparent',
              }}
              onMouseEnter={e => { if (!isActive) (e.currentTarget as HTMLButtonElement).style.color = 'var(--text-primary)' }}
              onMouseLeave={e => { if (!isActive) (e.currentTarget as HTMLButtonElement).style.color = 'var(--text-secondary)' }}
            >
              <span className="text-base">{tab.icon}</span>
              {tab.label}
            </button>
          )
        })}
      </div>

      {/* Active tab label */}
      <div className="flex items-center gap-2">
        <span className="text-xl">{activeTabData?.icon}</span>
        <h2 className="text-lg font-bold" style={{ color: activeTabData?.color }}>{activeTabData?.label}</h2>
        <div className="flex-1 h-px ml-2" style={{ background: `linear-gradient(to right, ${activeTabData?.color}30, transparent)` }} />
      </div>

      {/* Panel content */}
      <div>
        {loading && (
          <div className="flex flex-col items-center justify-center py-24 gap-4">
            <OrbitLoader size={96} label="Loading conference results" />
            <p className="text-sm font-medium" style={{ color: 'var(--text-secondary)' }}>Loading results...</p>
          </div>
        )}
        {!loading && (
          <>
            {activeTab === 'sponsor'   && <SponsorPanel />}
            {activeTab === 'speaker'   && <SpeakerPanel />}
            {activeTab === 'ticketing' && <TicketingFallback results={results} />}
            {activeTab === 'venue'     && <VenuePanel />}
            {activeTab === 'pricing'   && <PricingPanel />}
            {activeTab === 'gtm'       && <GTMPanel />}
            {activeTab === 'ops'       && <OpsPanel />}
          </>
        )}
      </div>
    </div>
  )
}

// Simple ticketing display (inline, no separate panel file needed)
function TicketingFallback({ results }: { results: AllResults }) {
  const data = results.ticketing
  if (!data) return <EmptyState label="Ticketing" emoji="🎫" />
  return (
    <div className="space-y-5">
      <div className="grid grid-cols-1 sm:grid-cols-2 lg:grid-cols-4 gap-4">
        {data.tiers?.map((tier: TicketTier) => (
          <div key={tier.tier} className="glass-card p-5 space-y-3 stagger-child">
            <p className="text-xs font-bold uppercase tracking-widest" style={{ color: 'var(--accent-cyan)' }}>{tier.tier}</p>
            <p className="text-4xl font-extrabold" style={{ color: 'var(--text-primary)' }}>
              <span className="text-xl font-semibold" style={{ color: 'var(--text-dim)' }}>$</span>
              {tier.price.toLocaleString()}
            </p>
            <p className="text-xs px-2 py-1 rounded-full inline-block" style={{ background: 'var(--bg-elevated)', color: 'var(--text-secondary)' }}>
              {tier.availability}
            </p>
            <ul className="space-y-1.5 pt-1">
              {tier.perks?.map((p: string) => (
                <li key={p} className="text-xs flex items-center gap-2" style={{ color: 'var(--text-secondary)' }}>
                  <span className="text-xs font-bold" style={{ color: 'var(--accent-green)' }}>✓</span> {p}
                </li>
              ))}
            </ul>
          </div>
        ))}
      </div>
      <div className="glass-card p-5">
        <p className="text-sm font-bold mb-1" style={{ color: 'var(--text-primary)' }}>Recommended Platform</p>
        <p className="text-sm font-semibold" style={{ color: 'var(--accent-cyan)' }}>{data.recommended_platform}</p>
        {data.notes && <p className="text-sm mt-3 leading-relaxed" style={{ color: 'var(--text-secondary)' }}>{data.notes}</p>}
      </div>
    </div>
  )
}

function EmptyState({ label, emoji }: { label: string; emoji?: string }) {
  return (
    <div
      className="flex flex-col items-center justify-center py-24 rounded-2xl gap-4"
      style={{ background: 'var(--bg-surface)', border: '1px dashed var(--border-subtle)' }}
    >
      {emoji && <span className="text-4xl">{emoji}</span>}
      <p className="font-semibold" style={{ color: 'var(--text-secondary)' }}>{label} data not available yet</p>
      <p className="text-sm" style={{ color: 'var(--text-dim)' }}>Run the agents first from the New Plan page.</p>
    </div>
  )
}
